sudo: required
services:
  - docker

before_install:
  - docker build -t pshyani/frontend -f Dockerfile.dev . 

script:
  - docker run pshyani/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "MyDocker-react"
  env: "MydockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-669590124548"
  bucket_path: "MyDocker-react"
  on:
    branch: master  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"